//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getMapByCentre", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class getMapByCentre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private webClient.ServiceReference1.soapAuth authorisationFieldField;
        
        private webClient.ServiceReference1.soapPoint centreFieldField;
        
        private int heightFieldField;
        
        private string imageFormatFieldField;
        
        private string layerFieldField;
        
        private webClient.ServiceReference1.soapMarker[] markersFieldField;
        
        private webClient.ServiceReference1.soapRoute[] routesFieldField;
        
        private int widthFieldField;
        
        private int zoomFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapAuth authorisationField {
            get {
                return this.authorisationFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.authorisationFieldField, value) != true)) {
                    this.authorisationFieldField = value;
                    this.RaisePropertyChanged("authorisationField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapPoint centreField {
            get {
                return this.centreFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.centreFieldField, value) != true)) {
                    this.centreFieldField = value;
                    this.RaisePropertyChanged("centreField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int heightField {
            get {
                return this.heightFieldField;
            }
            set {
                if ((this.heightFieldField.Equals(value) != true)) {
                    this.heightFieldField = value;
                    this.RaisePropertyChanged("heightField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string imageFormatField {
            get {
                return this.imageFormatFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.imageFormatFieldField, value) != true)) {
                    this.imageFormatFieldField = value;
                    this.RaisePropertyChanged("imageFormatField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string layerField {
            get {
                return this.layerFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.layerFieldField, value) != true)) {
                    this.layerFieldField = value;
                    this.RaisePropertyChanged("layerField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapMarker[] markersField {
            get {
                return this.markersFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.markersFieldField, value) != true)) {
                    this.markersFieldField = value;
                    this.RaisePropertyChanged("markersField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapRoute[] routesField {
            get {
                return this.routesFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.routesFieldField, value) != true)) {
                    this.routesFieldField = value;
                    this.RaisePropertyChanged("routesField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int widthField {
            get {
                return this.widthFieldField;
            }
            set {
                if ((this.widthFieldField.Equals(value) != true)) {
                    this.widthFieldField = value;
                    this.RaisePropertyChanged("widthField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int zoomField {
            get {
                return this.zoomFieldField;
            }
            set {
                if ((this.zoomFieldField.Equals(value) != true)) {
                    this.zoomFieldField = value;
                    this.RaisePropertyChanged("zoomField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapAuth", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapAuth : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string passwordFieldField;
        
        private string tokenFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string passwordField {
            get {
                return this.passwordFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordFieldField, value) != true)) {
                    this.passwordFieldField = value;
                    this.RaisePropertyChanged("passwordField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tokenField {
            get {
                return this.tokenFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenFieldField, value) != true)) {
                    this.tokenFieldField = value;
                    this.RaisePropertyChanged("tokenField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapPoint", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double latitudeFieldField;
        
        private double longitudeFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double latitudeField {
            get {
                return this.latitudeFieldField;
            }
            set {
                if ((this.latitudeFieldField.Equals(value) != true)) {
                    this.latitudeFieldField = value;
                    this.RaisePropertyChanged("latitudeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double longitudeField {
            get {
                return this.longitudeFieldField;
            }
            set {
                if ((this.longitudeFieldField.Equals(value) != true)) {
                    this.longitudeFieldField = value;
                    this.RaisePropertyChanged("longitudeField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapMarker", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapMarker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private webClient.ServiceReference1.soapIcon builtInFieldField;
        
        private int heightFieldField;
        
        private int offsetXFieldField;
        
        private int offsetYFieldField;
        
        private webClient.ServiceReference1.soapPoint pointFieldField;
        
        private string userDefinedFieldField;
        
        private int widthFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapIcon builtInField {
            get {
                return this.builtInFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.builtInFieldField, value) != true)) {
                    this.builtInFieldField = value;
                    this.RaisePropertyChanged("builtInField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int heightField {
            get {
                return this.heightFieldField;
            }
            set {
                if ((this.heightFieldField.Equals(value) != true)) {
                    this.heightFieldField = value;
                    this.RaisePropertyChanged("heightField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int offsetXField {
            get {
                return this.offsetXFieldField;
            }
            set {
                if ((this.offsetXFieldField.Equals(value) != true)) {
                    this.offsetXFieldField = value;
                    this.RaisePropertyChanged("offsetXField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int offsetYField {
            get {
                return this.offsetYFieldField;
            }
            set {
                if ((this.offsetYFieldField.Equals(value) != true)) {
                    this.offsetYFieldField = value;
                    this.RaisePropertyChanged("offsetYField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapPoint pointField {
            get {
                return this.pointFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.pointFieldField, value) != true)) {
                    this.pointFieldField = value;
                    this.RaisePropertyChanged("pointField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string userDefinedField {
            get {
                return this.userDefinedFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.userDefinedFieldField, value) != true)) {
                    this.userDefinedFieldField = value;
                    this.RaisePropertyChanged("userDefinedField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int widthField {
            get {
                return this.widthFieldField;
            }
            set {
                if ((this.widthFieldField.Equals(value) != true)) {
                    this.widthFieldField = value;
                    this.RaisePropertyChanged("widthField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapRoute", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapRoute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float distanceFieldField;
        
        private int durationFieldField;
        
        private webClient.ServiceReference1.soapPoint[] geometryFieldField;
        
        private webClient.ServiceReference1.soapRouteSegment[] segmentsFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float distanceField {
            get {
                return this.distanceFieldField;
            }
            set {
                if ((this.distanceFieldField.Equals(value) != true)) {
                    this.distanceFieldField = value;
                    this.RaisePropertyChanged("distanceField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int durationField {
            get {
                return this.durationFieldField;
            }
            set {
                if ((this.durationFieldField.Equals(value) != true)) {
                    this.durationFieldField = value;
                    this.RaisePropertyChanged("durationField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapPoint[] geometryField {
            get {
                return this.geometryFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.geometryFieldField, value) != true)) {
                    this.geometryFieldField = value;
                    this.RaisePropertyChanged("geometryField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapRouteSegment[] segmentsField {
            get {
                return this.segmentsFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.segmentsFieldField, value) != true)) {
                    this.segmentsFieldField = value;
                    this.RaisePropertyChanged("segmentsField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapIcon", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapIcon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string colour1FieldField;
        
        private string colour2FieldField;
        
        private string colourFieldField;
        
        private string hoverColour1FieldField;
        
        private string hoverColour2FieldField;
        
        private string rolloverColour1FieldField;
        
        private string rolloverColour2FieldField;
        
        private string textColourFieldField;
        
        private string textFieldField;
        
        private webClient.ServiceReference1.soapIconType typeFieldField;
        
        private bool typeFieldSpecifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string colour1Field {
            get {
                return this.colour1FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.colour1FieldField, value) != true)) {
                    this.colour1FieldField = value;
                    this.RaisePropertyChanged("colour1Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string colour2Field {
            get {
                return this.colour2FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.colour2FieldField, value) != true)) {
                    this.colour2FieldField = value;
                    this.RaisePropertyChanged("colour2Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string colourField {
            get {
                return this.colourFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.colourFieldField, value) != true)) {
                    this.colourFieldField = value;
                    this.RaisePropertyChanged("colourField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string hoverColour1Field {
            get {
                return this.hoverColour1FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.hoverColour1FieldField, value) != true)) {
                    this.hoverColour1FieldField = value;
                    this.RaisePropertyChanged("hoverColour1Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string hoverColour2Field {
            get {
                return this.hoverColour2FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.hoverColour2FieldField, value) != true)) {
                    this.hoverColour2FieldField = value;
                    this.RaisePropertyChanged("hoverColour2Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rolloverColour1Field {
            get {
                return this.rolloverColour1FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.rolloverColour1FieldField, value) != true)) {
                    this.rolloverColour1FieldField = value;
                    this.RaisePropertyChanged("rolloverColour1Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string rolloverColour2Field {
            get {
                return this.rolloverColour2FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.rolloverColour2FieldField, value) != true)) {
                    this.rolloverColour2FieldField = value;
                    this.RaisePropertyChanged("rolloverColour2Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string textColourField {
            get {
                return this.textColourFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.textColourFieldField, value) != true)) {
                    this.textColourFieldField = value;
                    this.RaisePropertyChanged("textColourField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string textField {
            get {
                return this.textFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.textFieldField, value) != true)) {
                    this.textFieldField = value;
                    this.RaisePropertyChanged("textField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapIconType typeField {
            get {
                return this.typeFieldField;
            }
            set {
                if ((this.typeFieldField.Equals(value) != true)) {
                    this.typeFieldField = value;
                    this.RaisePropertyChanged("typeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool typeFieldSpecified {
            get {
                return this.typeFieldSpecifiedField;
            }
            set {
                if ((this.typeFieldSpecifiedField.Equals(value) != true)) {
                    this.typeFieldSpecifiedField = value;
                    this.RaisePropertyChanged("typeFieldSpecified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapIconType", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    public enum soapIconType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        babushka = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        multi = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        poi = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        standard = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapRouteSegment", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapRouteSegment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private webClient.ServiceReference1.soapPoint centreFieldField;
        
        private float metresFieldField;
        
        private string routeDirectionFieldField;
        
        private string textInstructionFieldField;
        
        private int timeFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapPoint centreField {
            get {
                return this.centreFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.centreFieldField, value) != true)) {
                    this.centreFieldField = value;
                    this.RaisePropertyChanged("centreField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float metresField {
            get {
                return this.metresFieldField;
            }
            set {
                if ((this.metresFieldField.Equals(value) != true)) {
                    this.metresFieldField = value;
                    this.RaisePropertyChanged("metresField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string routeDirectionField {
            get {
                return this.routeDirectionFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.routeDirectionFieldField, value) != true)) {
                    this.routeDirectionFieldField = value;
                    this.RaisePropertyChanged("routeDirectionField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string textInstructionField {
            get {
                return this.textInstructionFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.textInstructionFieldField, value) != true)) {
                    this.textInstructionFieldField = value;
                    this.RaisePropertyChanged("textInstructionField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int timeField {
            get {
                return this.timeFieldField;
            }
            set {
                if ((this.timeFieldField.Equals(value) != true)) {
                    this.timeFieldField = value;
                    this.RaisePropertyChanged("timeField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getMapByCentreResponse", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class getMapByCentreResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private webClient.ServiceReference1.soapMapArea returnFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapMapArea returnField {
            get {
                return this.returnFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.returnFieldField, value) != true)) {
                    this.returnFieldField = value;
                    this.RaisePropertyChanged("returnField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapMapArea", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapMapArea : webClient.ServiceReference1.soapMap {
        
        private string encodedGraphicFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string encodedGraphicField {
            get {
                return this.encodedGraphicFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.encodedGraphicFieldField, value) != true)) {
                    this.encodedGraphicFieldField = value;
                    this.RaisePropertyChanged("encodedGraphicField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapMap", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(webClient.ServiceReference1.soapMapArea))]
    public partial class soapMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private webClient.ServiceReference1.soapBox boundingBoxFieldField;
        
        private int zoomFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapBox boundingBoxField {
            get {
                return this.boundingBoxFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.boundingBoxFieldField, value) != true)) {
                    this.boundingBoxFieldField = value;
                    this.RaisePropertyChanged("boundingBoxField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int zoomField {
            get {
                return this.zoomFieldField;
            }
            set {
                if ((this.zoomFieldField.Equals(value) != true)) {
                    this.zoomFieldField = value;
                    this.RaisePropertyChanged("zoomField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapBox", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapBox : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private webClient.ServiceReference1.soapPoint botRightFieldField;
        
        private webClient.ServiceReference1.soapPoint topLeftFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapPoint botRightField {
            get {
                return this.botRightFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.botRightFieldField, value) != true)) {
                    this.botRightFieldField = value;
                    this.RaisePropertyChanged("botRightField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapPoint topLeftField {
            get {
                return this.topLeftFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.topLeftFieldField, value) != true)) {
                    this.topLeftFieldField = value;
                    this.RaisePropertyChanged("topLeftField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="geocode", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class geocode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private webClient.ServiceReference1.soapAddress addressFieldField;
        
        private webClient.ServiceReference1.soapAuth authorisationFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapAddress addressField {
            get {
                return this.addressFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.addressFieldField, value) != true)) {
                    this.addressFieldField = value;
                    this.RaisePropertyChanged("addressField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapAuth authorisationField {
            get {
                return this.authorisationFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.authorisationFieldField, value) != true)) {
                    this.authorisationFieldField = value;
                    this.RaisePropertyChanged("authorisationField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapAddress", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string stateFieldField;
        
        private string streetFieldField;
        
        private string suburbFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string stateField {
            get {
                return this.stateFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.stateFieldField, value) != true)) {
                    this.stateFieldField = value;
                    this.RaisePropertyChanged("stateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string streetField {
            get {
                return this.streetFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.streetFieldField, value) != true)) {
                    this.streetFieldField = value;
                    this.RaisePropertyChanged("streetField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string suburbField {
            get {
                return this.suburbFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.suburbFieldField, value) != true)) {
                    this.suburbFieldField = value;
                    this.RaisePropertyChanged("suburbField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapGeocodeResult", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapGeocodeResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float accuracyFieldField;
        
        private webClient.ServiceReference1.feature featureFieldField;
        
        private bool featureFieldSpecifiedField;
        
        private webClient.ServiceReference1.soapGeocodedAddress geocodedAddressFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float accuracyField {
            get {
                return this.accuracyFieldField;
            }
            set {
                if ((this.accuracyFieldField.Equals(value) != true)) {
                    this.accuracyFieldField = value;
                    this.RaisePropertyChanged("accuracyField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.feature featureField {
            get {
                return this.featureFieldField;
            }
            set {
                if ((this.featureFieldField.Equals(value) != true)) {
                    this.featureFieldField = value;
                    this.RaisePropertyChanged("featureField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool featureFieldSpecified {
            get {
                return this.featureFieldSpecifiedField;
            }
            set {
                if ((this.featureFieldSpecifiedField.Equals(value) != true)) {
                    this.featureFieldSpecifiedField = value;
                    this.RaisePropertyChanged("featureFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapGeocodedAddress geocodedAddressField {
            get {
                return this.geocodedAddressFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.geocodedAddressFieldField, value) != true)) {
                    this.geocodedAddressFieldField = value;
                    this.RaisePropertyChanged("geocodedAddressField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapGeocodedAddress", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapGeocodedAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private webClient.ServiceReference1.soapPoint coordinatesFieldField;
        
        private webClient.ServiceReference1.soapStreet intersectingFieldField;
        
        private string numberFieldField;
        
        private string postcodeFieldField;
        
        private string stateFieldField;
        
        private webClient.ServiceReference1.soapPoint streetCoordinatesFieldField;
        
        private webClient.ServiceReference1.soapStreet streetFieldField;
        
        private string suburbFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapPoint coordinatesField {
            get {
                return this.coordinatesFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.coordinatesFieldField, value) != true)) {
                    this.coordinatesFieldField = value;
                    this.RaisePropertyChanged("coordinatesField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapStreet intersectingField {
            get {
                return this.intersectingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.intersectingFieldField, value) != true)) {
                    this.intersectingFieldField = value;
                    this.RaisePropertyChanged("intersectingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numberField {
            get {
                return this.numberFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.numberFieldField, value) != true)) {
                    this.numberFieldField = value;
                    this.RaisePropertyChanged("numberField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string postcodeField {
            get {
                return this.postcodeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.postcodeFieldField, value) != true)) {
                    this.postcodeFieldField = value;
                    this.RaisePropertyChanged("postcodeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string stateField {
            get {
                return this.stateFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.stateFieldField, value) != true)) {
                    this.stateFieldField = value;
                    this.RaisePropertyChanged("stateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapPoint streetCoordinatesField {
            get {
                return this.streetCoordinatesFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.streetCoordinatesFieldField, value) != true)) {
                    this.streetCoordinatesFieldField = value;
                    this.RaisePropertyChanged("streetCoordinatesField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public webClient.ServiceReference1.soapStreet streetField {
            get {
                return this.streetFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.streetFieldField, value) != true)) {
                    this.streetFieldField = value;
                    this.RaisePropertyChanged("streetField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string suburbField {
            get {
                return this.suburbFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.suburbFieldField, value) != true)) {
                    this.suburbFieldField = value;
                    this.RaisePropertyChanged("suburbField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="feature", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    public enum feature : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        placename = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        road = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        property = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soapStreet", Namespace="http://schemas.datacontract.org/2004/07/IG.CLP.BusinessLogic.com.whereis.ems")]
    [System.SerializableAttribute()]
    public partial class soapStreet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string directionalPrefixFieldField;
        
        private string directionalSuffixFieldField;
        
        private string fullNameFieldField;
        
        private string nameFieldField;
        
        private string typeFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string directionalPrefixField {
            get {
                return this.directionalPrefixFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.directionalPrefixFieldField, value) != true)) {
                    this.directionalPrefixFieldField = value;
                    this.RaisePropertyChanged("directionalPrefixField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string directionalSuffixField {
            get {
                return this.directionalSuffixFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.directionalSuffixFieldField, value) != true)) {
                    this.directionalSuffixFieldField = value;
                    this.RaisePropertyChanged("directionalSuffixField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fullNameField {
            get {
                return this.fullNameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameFieldField, value) != true)) {
                    this.fullNameFieldField = value;
                    this.RaisePropertyChanged("fullNameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nameField {
            get {
                return this.nameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nameFieldField, value) != true)) {
                    this.nameFieldField = value;
                    this.RaisePropertyChanged("nameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string typeField {
            get {
                return this.typeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.typeFieldField, value) != true)) {
                    this.typeFieldField = value;
                    this.RaisePropertyChanged("typeField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWhereIsAdapterService")]
    public interface IWhereIsAdapterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWhereIsAdapterService/getMapByCentre", ReplyAction="http://tempuri.org/IWhereIsAdapterService/getMapByCentreResponse")]
        webClient.ServiceReference1.getMapByCentreResponse getMapByCentre([System.ServiceModel.MessageParameterAttribute(Name="getMapByCentre")] webClient.ServiceReference1.getMapByCentre getMapByCentre1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWhereIsAdapterService/getMapByCentre", ReplyAction="http://tempuri.org/IWhereIsAdapterService/getMapByCentreResponse")]
        System.Threading.Tasks.Task<webClient.ServiceReference1.getMapByCentreResponse> getMapByCentreAsync(webClient.ServiceReference1.getMapByCentre getMapByCentre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWhereIsAdapterService/geocode", ReplyAction="http://tempuri.org/IWhereIsAdapterService/geocodeResponse")]
        webClient.ServiceReference1.soapGeocodeResult[] geocode([System.ServiceModel.MessageParameterAttribute(Name="geocode")] webClient.ServiceReference1.geocode geocode1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWhereIsAdapterService/geocode", ReplyAction="http://tempuri.org/IWhereIsAdapterService/geocodeResponse")]
        System.Threading.Tasks.Task<webClient.ServiceReference1.soapGeocodeResult[]> geocodeAsync(webClient.ServiceReference1.geocode geocode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWhereIsAdapterServiceChannel : webClient.ServiceReference1.IWhereIsAdapterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WhereIsAdapterServiceClient : System.ServiceModel.ClientBase<webClient.ServiceReference1.IWhereIsAdapterService>, webClient.ServiceReference1.IWhereIsAdapterService {
        
        public WhereIsAdapterServiceClient() {
        }
        
        public WhereIsAdapterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WhereIsAdapterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WhereIsAdapterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WhereIsAdapterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public webClient.ServiceReference1.getMapByCentreResponse getMapByCentre(webClient.ServiceReference1.getMapByCentre getMapByCentre1) {
            return base.Channel.getMapByCentre(getMapByCentre1);
        }
        
        public System.Threading.Tasks.Task<webClient.ServiceReference1.getMapByCentreResponse> getMapByCentreAsync(webClient.ServiceReference1.getMapByCentre getMapByCentre) {
            return base.Channel.getMapByCentreAsync(getMapByCentre);
        }
        
        public webClient.ServiceReference1.soapGeocodeResult[] geocode(webClient.ServiceReference1.geocode geocode1) {
            return base.Channel.geocode(geocode1);
        }
        
        public System.Threading.Tasks.Task<webClient.ServiceReference1.soapGeocodeResult[]> geocodeAsync(webClient.ServiceReference1.geocode geocode) {
            return base.Channel.geocodeAsync(geocode);
        }
    }
}
